[features]
seeds = false
skip-lint = false
[programs.localnet]
swap_remi = "2FJyhaV6H11ZexBUXtAZtYiaDmtqZBrKWVpFDRoCEWBt"

[registry]
url = "https://api.testnet.solana.com"

[provider]
cluster = "testnet"
wallet = "/home/cloud/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
